#Spring
spring:
  application:
    name: @artifactId@
  profiles:
    active: local-discovery
  #Zipkin
  zipkin:
    baseUrl: http://localhost:9411/
#General configuration
server:
  port: 8112
logging:
  level:
    org.springframework.cloud.gateway: debug
#Eureka
eureka:
  client:
    register-with-eureka: false
