#Spring
spring:
  application:
    name: @artifactId@
  profiles:
    active: local-discovery
#General configuration
server:
  port: 8112
logging:
  level:
    org.springframework.cloud.gateway: debug
